---
resources:
  - name: source-repo
    type: git
    source: {uri: 'https://github.com/kanak0304/ci-demo', branch: master}
  - name: cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true
    check_every: 10s # for demo
  - name: m2
    type: docker-image
    source:
      repository: making/m2
jobs:
  - name: unit-test
    serial: true
    public: true
    plan:
      - aggregate:
        - get: source-repo
          trigger: true
        - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: java, tag: 8-alpine}
          inputs:
          - name: source-repo
          - name: m2
          run:
            path: sh
            args:
              - -c
              - |
                cd source-repo
                ./mvnw test -Dmaven.repo.local=../m2/rootfs/opt/m2
  - name: deploy-to-cf
    serial: true
    public: true
    plan:
      - aggregate:
        - get: source-repo
          trigger: true
          passed: [ unit-test ]
        - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: java, tag: 8-alpine}
          inputs:
          - name: source-repo
          - name: m2
          outputs:
          - name: output
          run:
            path: sh
            args:
              - -c
              - |
                cd source-repo
                ./mvnw package -Dmaven.test.skip=true -Dmaven.repo.local=../m2/rootfs/opt/m2
                cp target/*.jar ../output/demo.jar
      - put: cf
        params:
          manifest: source-repo/manifest.yml
          path: output/demo.jar
          current_app_name: concourse-ci-demo
