---
resources:
  - name: source-repo
    type: git
    source:
      uri: https://github.com/making/ci-demo
      branch: master

jobs:
  - name: unit-test
    serial: true
    public: true
    plan:
      - get: repo
        trigger: true
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-alpine
          inputs:
          - name: souorce-repo
          run:
            path: sh
            args:
              - -c
              - |
                cd source-repo
                ./mvnw test
